### ISSUE TITLE
Why We Need Reform/Problem and Solution Page(s) - Decide division of info

### ISSUE THREAD

**Issue by jbernd** [mplauche/UpRise-website-2.0#11]
Figure out whether we should have a separate 'The Problem vs. The Solution'-type page or whether additional text should be added to "Why do we need campaign reform?" to make it serve the purpose, in consultation with Antonia

**Comment by jbernd** [comment]
I will draft a page that adds in various text we're excising from elsewhere and run it by Antonia

**Comment by jbernd** [comment]
Draft moving-around-ing at https://docs.google.com/document/d/1HBWNX-mbgHcRJq7hlFQMoV6Y62bqk5scSzTm0bOqZcM/edit#

**Comment by jbernd** [comment]
...still back-and-forthing in email...

**Comment by mplauche** [comment]
okay. I'm following comments, but backing out of discussion so there aren't too many chefs for the stew.

**Comment by jbernd** [comment]
...Antonia's got something new cooked up, which I believe she shall reveal soon. :)

**Comment by jbernd** [comment]
Now on home page anyway, except expanding on complementary-approaches, which I guess I'll have to find a place for elsewhere...?
