### ISSUE TITLE
Get Involved Page - Right Subbox - STAY INFORMED

### ISSUE THREAD

**Issue by mplauche** [mplauche/UpRise-website-2.0#13]
Pic: (this is just a placeholder)
![capture d ecran 2016-07-06 a 12 48 27 pm](https://cloud.githubusercontent.com/assets/12802756/16664661/ebc0a060-4435-11e6-9c2c-e8c30aadeda7.png)

Title: STAY INFORMED
The best defense against corruption are informed citizens. Stay up-to-date on breaking news, insider info, and actions you can take to get big money out of politics.

Button: STAY INFORMED
Button links to Stay Informed Page. (needs to be created)

**Comment by jbernd** [comment]
Needs a landscape-orientation pic!!!

**Comment by mplauche** [comment]
Try this - if it works, I'll clean it up
![capture d ecran 2016-07-14 a 9 05 34 am](https://cloud.githubusercontent.com/assets/12802756/16846683/46e585d4-49a2-11e6-97a3-ec7c36e9f431.png)

Or try this one:
![capture d ecran 2016-07-14 a 9 08 10 am](https://cloud.githubusercontent.com/assets/12802756/16846777/974ab6d4-49a2-11e6-9295-58e71a713ede.png)

Or this one (still just a placeholder, needs work):
![stayinformed1](https://cloud.githubusercontent.com/assets/12802756/16846976/980a7982-49a3-11e6-9e17-8a10acd4118d.png)

**Comment by jbernd** [comment]
Updated using the middle pic. I actually like the bottom one best for the purpose, but it's still not _quite_ big enough. (Needs to be at least 334 x 233. Preferably bigger, in case people click through to the fake page -- which still does happen if you click on the image, even though we killed the clickable box titles. :) ) (I have Plans for the top pic. :) )

**Comment by mplauche** [comment]
okay I have an idea for this pic that will work - thanks for the size - I wasn't sure how big it needed to be.

**Comment by jbernd** [comment]
Re: size -- it needs to be at least that _wide_, but it can be vertically shorter, as long as all three pics are the same aspect ratio. (So, frex, I had to cut off the sides of the pic under "Volunteer" to make it match the other two, but it would be reinstated as a wider-aspect pic if the other two were also wide-aspect.)

**Comment by mplauche** [comment]
see #7

**Comment by jbernd** [comment]
MAD on #7 : 'I'm not sure about the "sign up for the newsletter". I think its good for now, though a little sparse. What do you suggest?'

Me: I could add a line about following us on FB/Twitter, but then it would be getting outsizedly long and make the 'Donate' text box look really short. :) I think it's okay.
