### ISSUE TITLE
Stay Informed Page

### ISSUE THREAD

**Issue by mplauche** [mplauche/UpRise-website-2.0#14]
pic: image UpRise Flyers work well here.

Here are elements we need for this page, not clear yet on layout: 
Lots of repetition, so we can bip text from other parts of the webpage. 
1. Direct users (again) to Sign up for our Newsletter
   "Our monthly newsletter...."
2. Direct users to follow us on fb 
   "Follow us on fb for insider info, updates from our work on-the-ground with particular campaigns, breaking news and research on campaign spending, and more"
   1. Direct users to follow us on twitter
      "Follow UpRise on twitter for breaking news, articles, and actions around money in politics. Hear from a wide range of journalists, activists, and citizens working together to tackle corruption in our government. Be a part of the discussion and the movement."

**Comment by jbernd** [comment]
Is this supposed to be a separate page, or do you just mean the "page" that feeds the 'Stay Informed' grid box on the 'Get Involved' page? If the latter, do you want this text/image or the text/image you put in the ticket for the grid box?

**Comment by mplauche** [comment]
On the Get Involved page (#13) , there are three grid boxes, the right-most is about Staying Informed. 

I seem to recall in our last discussion that the Titles of each box would be dropped, to cheat the way that wordpress forces you to go to the page version of each grid box if you click on the title. 

So the grid box of Staying Informed will have 3 elements: A picture, a paragraph, and a button that says "Stay Informed".

If you click on the button that says "Stay Informed", it would go to a Stay Informed Page. 

The very vague notes at the top are laying out some basic elements of the Stay Informed page.

**Comment by jbernd** [comment]
Closing this, as we decided not to do it. :)
