### ISSUE TITLE
Home Page image/main box

### ISSUE THREAD

**Issue by jbernd** [mplauche/UpRise-website-2.0#15]
mock up with rotunda and changes to main text box (per other tickets) and send out for approval

**Comment by jbernd** [comment]
Draft in http://uprise.org/our-vision-version-two/

**Comment by jbernd** [comment]
BTW, the credit I added to the photo is kind of cheating, but it looked better shorter. :) 

(We didn't notice when looking at this before that WordPress was cropping the photo to a shorter height; I did a version pre-cropped so the credit would work.)

**Comment by mplauche** [comment]
thanks.

What does the rotunda look like when it is the backdrop (instead of baby blue?)

**Comment by jbernd** [comment]
Awful. :)
![screen shot 2016-07-14 at 1 23 01 am](https://cloud.githubusercontent.com/assets/11185056/16832924/9d96c5be-4961-11e6-83ff-85de190fc81a.png)

**Comment by mplauche** [comment]
Agreed! :)

**Comment by jbernd** [comment]
Working with crowd image for now, in public-but-not-linked version at https://uprise.org/our-vision-version-two/

Need to add a credit line to the photo.

**Comment by jbernd** [comment]
Credited, re-not-fuzzified, and set as actual home page image.
