### ISSUE TITLE
Overall Layout Changes - misc.

### ISSUE THREAD

**Issue by jbernd** [mplauche/UpRise-website-2.0#16]
Tracking:
- Add gradient to background
- Try new logo (mockup and screenshot for approval)

**Comment by jbernd** [comment]
Gradient done, using mods to background-color property for site (rather than background image). 

(Comment: I am getting heartily sick of the wordpress.com CSS customizer, which sometimes works and sometimes doesn't, so I don't know whether I'm doing the wrong thing or it's just ignoring me.)

**Comment by jbernd** [comment]
Screenshots of logo emailed. (But still needs mods to the logo image, which I should not be tasked with making.)

**Comment by jbernd** [comment]
Ensmallened new logo.

**Comment by jbernd** [comment]
Need to: Find a textured background? -- Mad, I feel like I remember you sending along a cloudy sky thing you wanted to try, but I can't find it. (I did a quick search for tiling skies but didn't find any I liked yet. They have to be tiling unless they are like a bajillion pixels by a bajillion pixels.)

**Comment by mplauche** [comment]
Ok. I think either background image (blue) or central image (rotunda) should be realistic photograph but not both. So I can look for skies but then the central image should probably be solid. 

The gradient is not working?
The grey texture is not working?

**Comment by jbernd** [comment]
The gradient is working in my browser. :) (And it can't be both at once, obviously; there's a screenshot with the grey texture in your email, in response to whatever message where you asked me to send you one...)

**Comment by jbernd** [comment]
If you mean, working for me, I think it signals boring-default, but if both you and Antonia like it, I don't feel that strongly.

**Comment by jbernd** [comment]
Antonia added new light-blue background with texture; closing now.
