### ISSUE TITLE
Home Page reorganization - Text Boxes

### ISSUE THREAD

**Issue by jbernd** [mplauche/UpRise-website-2.0#17]
Julia to mock up in a Google doc and send to Mad and Antonia for revisions-as-necessary:
- Move info from leftmost footer column about Campaign Services up to the lefthand middle-of-page text box (heading 'For Campaigns' or some such), revising as necessary
- Focus righthand middle-of-page text box on what we offer volunteers/the platform (snag now-unused text from elsewhere as necessary) (heading 'For Volunteers' or some such)
- Make leftmost footer column multi-purpose, including Search box and contact info but also "What's New" (will be, petition and book -- but what now? we can also include an iCalendar or EventBrite widget if we want to list speaking appearances and such)
- Tuck old text from Our Solution into 'Why do we need reform' or wherever needs better text? (see separate ticket)

(Keeping in mind that the three-column footer appears on all pages, not just the home page)

**Comment by jbernd** [comment]
Draft moving-around-ing at https://docs.google.com/document/d/1HBWNX-mbgHcRJq7hlFQMoV6Y62bqk5scSzTm0bOqZcM/edit#

**Comment by jbernd** [comment]
By the way, we can also add 'Testimonial boxes' under the middle-of-page boxes (still two-column). Not useful for much besides quotes, 'cause even if you don't put in a name it still includes the em-dash. :) But we could put rotating fun quotes there if we like. (It automagically pulls a random two, if we have a bunch.) Can include images.
![screen shot 2016-07-08 at 3 10 55 am](https://cloud.githubusercontent.com/assets/11185056/16684423/de231d50-44b9-11e6-97b1-f8d3064470d5.png)

**Comment by mplauche** [comment]
I like the idea of rotating quotes. PS I got permission from Zephyr to use this one:

“The best defense against big money is people.” 
- Zephyr Teachout, Anti-corruption crusader and 2016 candidate for 19th district of NY

yay!!!

**Comment by mplauche** [comment]
Julia- since we only have one quote, I'd like to use it on the Donate page. (#12)
Let's save the rotating quotes (awesome) for when we have more than one, okey dokey?

**Comment by jbernd** [comment]
Updated text-moving-around-ing suggestions at https://docs.google.com/document/d/1HBWNX-mbgHcRJq7hlFQMoV6Y62bqk5scSzTm0bOqZcM/edit# -- basically assumes the 'Our Vision' part will stay in the main text box (in the featured image) and adds 'More From UpRise' to the lefthand footer column, which is so far just the video.

**Comment by jbernd** [comment]
Re-re-re-reorganized per convo with Mad: https://docs.google.com/document/d/1HBWNX-mbgHcRJq7hlFQMoV6Y62bqk5scSzTm0bOqZcM/edit

**Comment by jbernd** [comment]
Leftmost footer widget box now has "Our Vision", "Contact UpRise", and "Search Our Site". Additional rearrangements pending email back-and-forth.

**Comment by jbernd** [comment]
Done been implemented by Antonia, one way or another.
