### ISSUE TITLE
Main Page - Add Movie

### ISSUE THREAD

**Issue by mplauche** [mplauche/UpRise-website-2.0#4]
Let's try putting the movie on the front page next to text box. 

Layout might look something like this:

![capture d ecran 2016-06-15 a 10 10 10 am](https://cloud.githubusercontent.com/assets/12802756/16630183/250f76de-436e-11e6-9f18-b8d98ef1bb9f.png)

Alternatively (and this might work better), it could be IN the current "Our Vision" text box.

**Comment by jbernd** [comment]
Draft in http://uprise.org/our-vision-version-two/

**Comment by jbernd** [comment]
We need to do something about the fact that uprisecampaigns.org/go routes to a closed Indiegogo campaign! It needs to route to uprise.org/get-involved/ or the home page.

**Comment by mplauche** [comment]
Good catch - Emailed Barath about the reroute

**Comment by jbernd** [comment]
Will be moved to lefthand universal-footer column?

**Comment by jbernd** [comment]
Movie is in there (note I changed which frame is the "poster image"); still need to reroute from /go!!!
