### ISSUE TITLE
Main Page - Text box

### ISSUE THREAD

**Issue by mplauche** [mplauche/UpRise-website-2.0#5]
Change to:

---

Our Vision 
[MOVIE]

With your support, we can FREE political campaigns from dependence on big donors. (big font)

[Donate Button] 

---

If user clicks on [MOVIE], it plays.
If user clicks on [Donate Button] it goes to Donate Page.

**Comment by jbernd** [comment]
Draft in http://uprise.org/our-vision-version-two/ A couple queries before I throw it at Antonia:
- I think we may need another line of text above the video. I don't like that we have the title 'Our Vision' on a video of a giant political corruption machine. :) (Alternatively, it might be possible to use a different still from the video as the  image, but all the supposed solutions on the interwebs don't work (as usual).)
- However: If we add more text, the text box gets bigger, and it's already obscuring a lot of inspirational dome. :) Maybe make the video smaller?
- I'm not sure how I feel about the capital FREE. :)

**Comment by jbernd** [comment]
...in fact, I rather favor figuring out how to do a different still, if Matthew can manage it. The angry robot does rather detract from the inspirationalness of the dome. :)

**Comment by jbernd** [comment]
Another alternative would be to rename the page so the text box isn't headed 'Our Vision'. But I like being aspirational! Maybe the movie should go under "Why do we need campaign reform?" instead?

**Comment by jbernd** [comment]
Okay, I found a way to change the poster image for the video! Had to upload the video to the Media Library rather than embedding from YouTube. 

However, along the way I had added "Less Money ~ More Wins ~ Healthy Democracy" above it, and I do rather like it that way. However, with the current size the video is at, it does mean the text box almost fills the right side of the dome image. Smaller video maybe? (I unbolded and changed the wording of the line under the video to make it all fit on one line in the usual view. I like the wording less well, but the aesthetic improvement is significant. :) )

**Comment by mplauche** [comment]
Here are some notes for a very bare bones look which I would like to see. I'm curious what a very minimal page looks like (something like represent.us). 

---

Cut "Our Vision"
Cut "Less money.... democracy"
Instead put "Together ...." Above video
Increase font of "Together we can..."
Maybe even bold it too.

Movie looks good
Donate button looks good.

---

But I wrote these before I saw your notes above and I'm open to other directions. 

I like "Less money, more wins..." too. I'm ok with that.
I didn't notice the "FREE", of course that can be "free"

Smaller video is okay with me. 

Another place for video could be in the mystery third column next to FB and TW. 

I saw another website this morning that used this third column to put their mission statement. I think that really worked because it's on every page. We could do the same. And the video could go down there so its on the home page (and every page for that matter) so newbies can easily find and watch it but its small so it doesn't take up much real estate and then text box could go back to Antonia's text and a donate button.

**Comment by jbernd** [comment]
Assuming we'll go back to the old text. Sorta mockup updated at https://docs.google.com/document/d/1HBWNX-mbgHcRJq7hlFQMoV6Y62bqk5scSzTm0bOqZcM/edit#

**Comment by mplauche** [comment]
I still would really like to see a minimal version here  a la represent.us - image at the top of (#15) or check out:  https://represent.us

But it looks like we are moving back to original version - heavy on text.  Can you update me on what the thinking is? 

Can we put the Donate button back here, instead of (or in addition to) hyperlinked red text ?
Its important that people with 30 seconds, visiting this site as a favor to Morgan, can quickly locate a Donate Button without scanning a paragraph or even a menu. 

Possible Minimal version for Uprise:

---

[MOVIE]

With your support, we can FREE political campaigns from dependence on big donors. (big font)

[Donate Button]

---

**Comment by jbernd** [comment]
Back to video-in-the-box per convo with Mad, plus retitled, etc.: https://uprise.org/our-vision-version-two/

I also reinstated the big red Donate button in the box on the live version of the home page, now going to the Donate page. (Previously it went directly to PayPal.)

**Comment by jbernd** [comment]
Done and set as actual home page.
