### ISSUE TITLE
Contact Us Page - CUT

### ISSUE THREAD

**Issue by mplauche** [mplauche/UpRise-website-2.0#6]
I think our email is scattered about, so people can find it if they need to email. 

We don't need a page for CONTACT US

**Comment by jbernd** [comment]
Done. The page still exists and is public viewable (in case there's links I don't know about), but isn't linked from the menu (or anything on the site that I know of).

I added the mailing address to the leftmost column of the footer widget, under Campaign Services -- it doesn't really go there, but it'll do for now.
