### ISSUE TITLE
Get Involved Page - Top Big Intro Text Box

### ISSUE THREAD

**Issue by mplauche** [mplauche/UpRise-website-2.0#7]
Overall Layout - Let's try the Outreach page layout below:

![capture d ecran 2016-07-06 a 11 59 34 am](https://cloud.githubusercontent.com/assets/12802756/16630901/286bbd26-4371-11e6-8b8a-1f69c1e70cd1.png)

It has a big intro text box that spans three columns. Then three sub boxes side by side. (see issue #8)
Title of big intro text box should be: "Get Involved"
Big intro text box should read:

---

“The best defense against big money is people.” 
- Zephyr Teachout, Anti-corruption crusader and 2016 candidate for 19th district of NY

UpRise works hard to reduce corruption in politics by ensuring that candidates today have viable alternatives to reliance on big donors. Your generous support equips today’s candidates with the tools they need to run people-powered campaigns and win. 

Sign up for our newsletter, it's the easiest way to support our fight to free campaigns from their dependence on big money. In addition, each monthly newsletter keeps you posted about insider updates, the issue of money in politics, and actions you can take to make a difference.

---

"Sign up" above links to our current Sign Up page (the constant contact one). 
"Sign up for our newsletter" - should also be bold and bigger font.

**Comment by jbernd** [comment]
Done-ish at http://uprise.org/get-involved/ . I put the newsletter signup as the third grid box (it has to be rows of three, so it made sense to me! -- individual page at https://uprise.org/get-involved/sign-up-for-the-newsletter/ ), but of course the text is longer than the others so revision may need to happen. I made spiffy buttons for each of the grid boxes, but there's nothing to be done about the fact that the link in the title of each box just takes you to the child "page" corresponding to the box. 

Still need to do: Any text revisions to align with whatever we do elsewhere about donate pitches, also to equalize text lengths.

**Comment by jbernd** [comment]
Oh yeah, also need: Good picture for newsletter. For now I've got the business cards, which is not terribly inspiring. :)

**Comment by jbernd** [comment]
A couple more queries:
- Do we want to incorporate items (2) and (3) under "Other ways you can get involved" from the older version of the support/donate/get involved page at http://uprise.org/supportget-involved/ ? (I think those items were all your suggestions; do you disagree with yourself or have you just not decided where to put them? :) )
- Do we want to say "there's many ways to become a member" or do we want to leave it implied (though not explicitly stated) that members are the people who donate?

**Comment by jbernd** [comment]
Re: Many ways to become a member -- I'd just like something that directs people's attention down the page, as the grid boxes may be below the fold (even after I deleted the Like button and Sharing buttons...)

**Comment by mplauche** [comment]
Sorry - there is some confusion because I ran out of steam before I finished all 3 boxes. Here is what I am going for for this page:

https://www.issueone.org/get-involved/

It has a big text box telling people to Get Involved.  I want to do the same.
Then it has a big text box telling people to Sign Up. I want to do the same.
Then it has 3 boxes with 3 actions. Ours would be Volunteer, Donate, Stay Informed.
Then it has a big text box for special cases "are you a former elected official". I think we should also have a big text box for our special case: 

"Working on a campaign right now? Know someone who’s running for office? Running for office yourself?Get in touch about how we can help! staff@uprise.org"

Does that make sense?

**Comment by mplauche** [comment]
Re your other questions:

J - "Many ways to become a member"

m - I think "member" is someone who donate, so I'm saving that terminology for the Donate Page. For this page (and thoughout the website), I'm focused on trying to get as many emails and donations and followers as I can from anyone who visits the site. 

J - "there's nothing to be done about the fact that the link in the title of each box just takes you to the child "page" corresponding to the box."

m - That's ok for Donate and Stay Informed, but its a little weird for Volunteer (which I would have liked to have routed directly to the Constant Contact Form). Oh well, I guess we will have to make a Volunteer page (which you did). 

J - "Do we want to incorporate items (2) and (3)"

m- I want to incorporate almost everything from that page (I might have just not gotten to it), but I am not sure here what you mean by (2) and (3).  Clarify?

**Comment by jbernd** [comment]
...keeping in mind that the Teachout quote is now on both the Get Involved page and the Donate page.

**Comment by mplauche** [comment]
Yeah, good point. Can we cut it from here, and keep it on the Donate page?

**Comment by jbernd** [comment]
Mad -- are you still thinking you want a big thing about 'Sign Up for the Newsletter' at the bottom of the top text box, as well as in the righthand grid box?

**Comment by jbernd** [comment]
(crammed the bit about "already working on a campaign?" into the Volunteer bit while I was fixing per Morgan's request. doesn't cover all the promote-us angles, but it's something. :) )

**Comment by mplauche** [comment]
This page is looking good.
I'm not sure about the "sign up for the newsletter". I think its good for now, though a little sparse. What do you suggest?

Julia - I have images for these three actions. Try these out, I hope they look good.
![stayinformed_handdown_landscape](https://cloud.githubusercontent.com/assets/12802756/16922306/e572d006-4cc9-11e6-8fd2-26fc5ff5c17a.png)
![volunteer_landscape](https://cloud.githubusercontent.com/assets/12802756/16922313/ea1d44d8-4cc9-11e6-8be8-8d51c1ae889f.png)
![donate_landscape](https://cloud.githubusercontent.com/assets/12802756/16922320/edf1bac6-4cc9-11e6-936b-ee14068bdbec.png)

**Comment by jbernd** [comment]
New pictures inserted. Very nice. :)

**Comment by mplauche** [comment]
whew. I'm glad they look good. I think so too.

**Comment by mplauche** [comment]
This is minor, but for the top paragraph of this page, it might be nice to have an overview that welcomes peeps to page and describes all the nice things they can do to help out.  Below is a possibility, though something friendlier/less dry might be better. (some of this text was proposed before but morgan had concerns with, but I think its okay now?)

“The best defense against big money is people.”

Zephyr Teachout, Anti-corruption crusader and 2016 candidate for 19th district of NY

UpRise works hard to reduce corruption in politics by ensuring that candidates today have viable alternatives to reliance on big donors. Volunteer to help a candidate you care about, and become part of the solution. Donate to UpRise today so we can equip today’s candidates with the tools they need to run people-powered campaigns and win.

Sign up for our newsletter, it's the easiest way to support our fight to free campaigns from their dependence on big money. In addition, each monthly newsletter keeps you posted about insider updates, the issue of money in politics, and actions you can take to make a difference.

**Comment by jbernd** [comment]
Done, except the last sentence, which is too repetitive with what's already in the Stay Informed box.
