### ISSUE TITLE
Get Involved Page - Leftmost Subbox - VOLUNTEER

### ISSUE THREAD

**Issue by mplauche** [mplauche/UpRise-website-2.0#8]
Leftmost subbox:
Pic: [Happy waving robot who is a campaign volunteer -  as placeholder]
Title: VOLUNTEER
Text: Help us build a platform, help us build a movement! 
Help out on a particular UpRise campaign. Can you join our team? 

Button: Contact us
"Contact Us" button links to Constant Contact Page (for now).

**Comment by jbernd** [comment]
In some previous incarnation, we were worrying about the difference between 'volunteering for UpRise' (i.e., helping us as an org) vs. 'volunteering on an UpRise campaign' (i.e., joining the platform/signing up to help on an electoral campaign). Are these being deliberately blended here? Or trying to leave off the volunteer-for-an-electoral-campaign part until we have a platform? Or...?

**Comment by jbernd** [comment]
Version up at https://uprise.org/get-involved/volunteer/ -- the Contact Us is a mailto for staff@uprise, which makes more sense than Constant Contact IMO. (However: There is no way on Ja's green earth to make a mailto open a new tab. Sigh.)

Need to: Revise wording per above query and get a landscape-oriented image.

**Comment by mplauche** [comment]
Yes, I did blend into one action - Volunteer - which either way directs people to contact us. 

I need 3 clear actions but I am open to changes. 

Try one of these as a placeholder image.
![capture d ecran 2016-07-06 a 12 44 54 pm](https://cloud.githubusercontent.com/assets/12802756/16664157/bb978e78-4433-11e6-85b4-8c752f4ca373.png)

![capture d ecran 2016-07-06 a 12 46 53 pm](https://cloud.githubusercontent.com/assets/12802756/16664195/edb4a4f4-4433-11e6-9df9-c694c71780b8.png)

**Comment by jbernd** [comment]
added text and fixed image aspect.
