### ISSUE TITLE
Get Involved Page - Middle Subbox - DONATE

### ISSUE THREAD

**Issue by mplauche** [mplauche/UpRise-website-2.0#9]
Pic: 
![money1](https://cloud.githubusercontent.com/assets/12802756/16631719/5cdcae2c-4375-11e6-837a-e3f6cb2c62f7.png)
Title: DONATE
Donate to support our work! UpRise depends on small contributions from members to disrupt the influence of big money in politics. Help us by donating today. 

Button: DONATE
Button links to Donate Page.

**Comment by jbernd** [comment]
Done-ish at https://uprise.org/get-involved/donate/ . I used a different image since it appears much bigger!

Need to do: Revise text according to whatever pitch angle we decide on.

**Comment by jbernd** [comment]
Mad, did you want a robot pic here?

**Comment by mplauche** [comment]
yeah - i guess I need to figure out a robot picture with money here. I have an idea - I'll work on it...

**Comment by jbernd** [comment]
Isn't there a moment in the video where a happy UpRise robot pops up from being buried under a pile of money?
